language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- npm run codeclimate
env:
  global:
  - secure: iKDGilPnBtCI0pQXuxmIij9a/j+ZCDRxmbW/cSefMwJtSbAntgqEXm0KGDlGpEQbbC3LfdiyWo9Wves89Lp+L9eoKgG0LwjRbhboByGupieQsAzz3Q/01ICIz4G7hMILbbK+R3cdZtf/tk1JTtWmT0berIEW9S3e/nM8mx15IVu3yEFQ38hpXK0Dd8fua92sqNGZU02qv+PFRDw11RmSFJoZJc1pZBc7GJLctCva7sed5JgEWVQMqd2yBpjN4L82+fjFrAqcrbSLZBce3tOGG7TXKnVgqmXdWulVeuxBMzLhGnrOxqiChoamj92u6fUg+96H5BEF03L5ShX+MPPm/Xsi2cJ2jfZpoiLpwgKut3SGRJGSggNXfkdaAJD5m4o+IUkaaZpYWbPVvBUmAPg4wDzeASY3EgQ9uMSLhuS70FhdGNaAquHLs2QheGrSlfwJb6H4q/ZErzToEEtFF1P2cTck+5MXr8OrGOM30/kcVdcSmpIt+gGnQow0icbZIjrzzPhID6cvEInsMqoqicwr+rcZFT4Ss8HLZwG2sb4YNMaD8xlN8Zxp8n8NyYZ3khyQer9OGrC3vdf/MNo60g+Ok3mtFa8KupSmVcws7JVu5LhuIgQDVK0R7UUO7RbNfxBdd5viAVt5aWHbihi1Jt6/YUOkN0HKcTESYbkfTCWwtAM=
  - secure: GAkCFbjGEC0imHOViteBtW6mBGP5ZS4D2OITuiaIRrSw3ehfouFFHgysOBoS8cigXqQ4v/TnpNg14UnsqCmAzw6uL+CgdHhe0ZaVeVYpC1ze8BMh1yWVI5zu42+EidSNJhaD4s93TloS2aRiaum8T0sCnGg24Nhkp2xwT4v8Q/K9Uh2DTvFItuESi7K/yBRd1E0tzVrNR/PnYy0SgSRBxWRMY/9Ws5Z2xCX924SR006S1z+FTOX3/hqJCWTTBTJBtk4gHA32uuUgEn3zHl0Wte+TYlKzBW0u4Ab6LQwNkVs47Ehyp3Xfevu80ANBTx6DYI3bQkcduhsjDQQ/lIjPvVi5mCPusgNhcPrRbxu7idsFDIVhSJmeUx3SqWLORON6pPySJ3XpQ4vtn8O8ob+WMcJippvdt0cM/E6I2QbN8JVQF04Gw9OPSXwIdJi7XJOdHDgfk8gMdn6XVzFyeoGQAWGb6EYCdQU8Bt4xM6qpu5NKaD9qkt5ciLCHPbr0K0ArduAXAnynyV/F3Q8ks4t62+34ybrekvo9weJX7dn33s9pW9dLvmgyU/5W6GzaatDwvJCGg7Q0gz9C3NOKjjmrKPIJGglapo73oAhe6ElxxP5kiwW0nN4nyogPBnrUQuJb9PF8S42MgiyMIBBi3TB/rbHQsVyaPwQM2/lmBPa4GDU=
