language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
- npm run coverage
- npm run codeclimate
env:
  global:
    secure: iKDGilPnBtCI0pQXuxmIij9a/j+ZCDRxmbW/cSefMwJtSbAntgqEXm0KGDlGpEQbbC3LfdiyWo9Wves89Lp+L9eoKgG0LwjRbhboByGupieQsAzz3Q/01ICIz4G7hMILbbK+R3cdZtf/tk1JTtWmT0berIEW9S3e/nM8mx15IVu3yEFQ38hpXK0Dd8fua92sqNGZU02qv+PFRDw11RmSFJoZJc1pZBc7GJLctCva7sed5JgEWVQMqd2yBpjN4L82+fjFrAqcrbSLZBce3tOGG7TXKnVgqmXdWulVeuxBMzLhGnrOxqiChoamj92u6fUg+96H5BEF03L5ShX+MPPm/Xsi2cJ2jfZpoiLpwgKut3SGRJGSggNXfkdaAJD5m4o+IUkaaZpYWbPVvBUmAPg4wDzeASY3EgQ9uMSLhuS70FhdGNaAquHLs2QheGrSlfwJb6H4q/ZErzToEEtFF1P2cTck+5MXr8OrGOM30/kcVdcSmpIt+gGnQow0icbZIjrzzPhID6cvEInsMqoqicwr+rcZFT4Ss8HLZwG2sb4YNMaD8xlN8Zxp8n8NyYZ3khyQer9OGrC3vdf/MNo60g+Ok3mtFa8KupSmVcws7JVu5LhuIgQDVK0R7UUO7RbNfxBdd5viAVt5aWHbihi1Jt6/YUOkN0HKcTESYbkfTCWwtAM=
