language: node_js
node_js:
- '7'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@4
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
env:
  global:
  - secure: TFnVAoSlLDw2e5LruRlJizME7+7P+0a1EOmBfDLtYm0AeEpkCXMrocNi8VlmW+W8PLIUalaMZ9DFKacgS7uzLwyXQPPLubBIU+knioD0Nutoo2usw9gEvTVVYM5lQ4GRv8BXcLlIb0YciPrn3Agc71OHrBloyKQRhbCA7pAyRTYUTJLMIH6YUAASPbc+qaWq5a45SdiFznhwyD4un3a2IC/jvLcOM2MCwxChqlHJ9JibrDj/1h/BUqoftou1YPQFIdz0jOl8LXjl1+AU+vuaVcD2TFNaWjyDFJpKRArLeLgc3L7nVMpgPDDFT4YeWbHJmWXwWImhEGcXtGKrJ3dd1zmUNViUz8OozGz5cYoO8QLOhFBL+5jqbkurFetNGXlFf3LeYVmUInwcIyu7nfOJFgFsiUYe2UOttASZ03zq0v87b7AFcjWpqPZo9grpY1nyh5RjDql3vDZIckI2BTGeBLSFbNbm2Hg+nJ5Pd6cWrlj9dpstWNFAt+E4uTiyJAH5/W8JIz7SH8CN7myl6p7Ei3E4HJEGvX51SAc7DVB00LRjIy6ThVjL+EnfNntwHAWejMAGF1mIdmVlG/NoNGUSuEqdyEme8KVCfV3ZeQS1FeZbpdvVZIFklRIwmrcgxhBn3OgqUb8yVyfP7ZhxfZju6ce/66IryzXKKda7knmiFSc=
  - secure: RSZTj7JwTRa5+0Ge71zS0N0qeOkwRQR9SbDKeVGLDJtC/LVzSxVdkQ67PJIxoH+vjZiVoxjfH5tA8ChIxP4i58COIYSCey9k8IHY/jZtaQeSgFIwnBF84WZ/rW+JLooj83UBc4mwr+BlDWC1YbSrw7fnFMQWwMgkfFToiqfr4AYelYNWLfg2ibDKKrTqZAbYWFOJlikuNDJRHgdGCqWHCHjnR/wCPbDb9NO7EbNCT/EnRo1/6Y50k7VDnctvxi5be9wI2qG9W9lUZ7KbxiC4tbfuRgfpIi0N4ECwWkcfws1kD2fi3DGS8+E723N79YU6ZzgxhGtF4zvHJTZox6wPWxQDrMY1odycf4DcEbdqZkJL8wg0xe4aU+A9fIvFe7B5QUq3gXZ5U7u4p+zUvmHzeHTW1PIlAuozbHvaRX4m5KxuJVo3pXxWVb0e2njoKQhiDy4biKo5kGIhf+6KAFp+vYATIo75N2tyZBPnuwYzUwQczeMvZWVV3BpApxsMbx8dpb73Sik1mfy50w4eKZMvpVS9HxCaVQScveKTugh95SPvX/u4QqNgFrR5OzmlE5ZPR/cVgUl4qpi3d94aY33chKnApitOE8kGM9Z0/qCOFNVUNnjY3eGdYO7fHC4Go8X4FLLgN1VrlmGQu42m3vFro3mve4e0FGNtcrj+fKcO89E=
  - secure: qeeJIwsWrlbHPS67BokgToh0CoflnWCVbfSsnc1sLsy51KQ1dOw04nwVGj74KXbetaRMqbtFXzutIZPwuR/MBP6QkWr0Vd7ne/2pCEQHFcMb96nXxHxbA2KPEQxn/sEtv43j8Uol7J73Cbv/MdYr0/5FVRdIV5aVUzr8ll1rNo0ywucUXWbfPv2RjO5DIqzAmYpNkwDRu5RQbAXXv2ckQzJp84d+0ZJnpoaL8d7U8B7iqWIyj1D67b2k7EuRNh4gIiP5Db2HvoycjAwzguhFOqoi3wTyf74eVt7ZAkVmOgyDe13uUiRo7uBQponZsc+yrkJZTucpS8ymwbTdDB7jBGVqeToGWdddSgdz8YQFWUqnFCz7gbg5f14RLzH0k56RfI5HzUMvtZYO/DJqMZuvDMsI61s6j4XFR4SoKJbgvTGcv7Ra9XJgtGDNS/nBDFHmEzxIGspFUK8XC+j5HEK4u8lWf8kr6x/3jHf8tKT1TUaQMtXemF3o4Ty/9QWchXXeQS4L9/OItPyHXOYtGEvbkd4ch2vxyENKi8QiIj/Vc33lLE1XVbFpbAiYKhkjVlBOZ2vtVQTzrWqWCeryptHCN0KP+EVFnHLPWfAgzg4JPJbYH4g74K9dccRSn6GsipcRU/UX2MNgGSRN795/eCo215Yw5EDY7pwkFrX61FwlCL4=
